apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: k8s-vpa 
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       nginx-deployment
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      mode: "Auto"
      controlledValues: "RequestsAndLimits"
      minAllowed:
        cpu: "10m"
        memory: "5Mi"
      maxAllowed:
        cpu: "500m"
        memory: "128Mi"
      controlledResources: ["cpu", "memory"]
  updatePolicy:
    updateMode: "Auto"